name: Build and Deploy
on:
    push:
        branches:
            - main

permissions:
    contents: write
    pages: write

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install Rust
              run: rustup override set stable

            - name: Install WASM support
              run: rustup target add wasm32-unknown-unknown

            - name: Build
              run: cargo build --release --target wasm32-unknown-unknwon
            
            - name: Prepare Deployment Directory
              run: |
                mkdir -p ./deploy
                cp ./target/wasm32-unknown-unknwon/release/macro-game.wasm ./deploy/
                cp index.html ./deploy/

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: ./deploy